server:
  port: 8081

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/spendsmart_auth_db
    username: root
    password: Abhishek@2003
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: kushwahaabhishek10k@gmail.com
    password: "wogm jnvp bzdq ydqt"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

app:
  otp:
    expiry-minutes: 10
    from-email: kushwahaabhishek10k@gmail.com

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

  instance:
    hostname: localhost      
    prefer-ip-address: true
