server:
  port: 8088

spring:
  application:
    name: notification-service

  datasource:
    url: jdbc:mysql://localhost:3306/spendsmart_notification_db
    username: root
    password: Abhishek@2003

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: kushwahaabhishek10k@gmail.com
    password: wogm jnvp bzdq ydqt
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true