server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:

        # ✅ Test route
        - id: test-route
          uri: http://httpbin.org
          predicates:
            - Path=/test

        # ✅ Auth Service
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

        # ✅ Expense Service
        - id: expense-service
          uri: lb://EXPENSE-SERVICE
          predicates:
            - Path=/expenses/**

        # ✅ Income Service
        - id: income-service
          uri: lb://INCOME-SERVICE
          predicates:
            - Path=/income/**

        # ✅ Category Service
        - id: category-service
          uri: lb://CATEGORY-SERVICE
          predicates:
            - Path=/categories/**

        # ✅ Budget Service
        - id: budget-service
          uri: lb://BUDGET-SERVICE
          predicates:
            - Path=/budgets/**

        # ✅ Analytics Service
        - id: analytics-service
          uri: lb://ANALYTICS-SERVICE
          predicates:
            - Path=/analytics/**

        # ✅ Recurring Service
        - id: recurring-service
          uri: lb://RECURRING-SERVICE
          predicates:
            - Path=/recurring/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    hostname: localhost
    prefer-ip-address: true