server:
  port: 8082

spring:
  application:
    name: expense-service

  datasource:
    url: jdbc:mysql://localhost:3306/spendsmart_expense_db
    username: root
    password: Abhishek@2003
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    hostname: localhost
    prefer-ip-address: true