server:
  port: 8085

spring:
  application:
    name: budget-service

  datasource:
    url: jdbc:mysql://localhost:3306/spendsmart_budget_db
    username: root
    password: Abhishek@2003
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

app:
  messaging:
    notification:
      async-enabled: false
      exchange: spendsmart.notification.exchange
      routing:
        budget-alert: notification.budget.alert

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    hostname: localhost
    prefer-ip-address: true
